# Generated by Django 4.2.5 on 2023-09-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("slug", models.CharField(max_length=100)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
